### ISSUE TITLE
Research: IDE create JAR, automate generating VCs

### ISSUE THREAD

**Issue by drholly77** [rhit-csse-projects/RESOLVE#10]
Research if/how-to have IntelliJ create JAR of the system
If it's possible use JAR to write a Linux shell script to generate VCs for all the .rb files in the current RESOLVE-Workspace
Here's a [link to a video](https://rose-hulman.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d8055342-1804-4eea-a49d-b1f80117ebe6) with more details

- [x] Jar the project
- [x] Write the shell script to run the jar file on all .rb files
- [x] Create Test cases to affirm VC generation is correct
- [x] Integrate the shell script into Github Actions

**Comment by AdityaSenthilvel** [comment]
- [ ] Jar the project
- [ ] Write the shell script to run the jar file on all .rb files
- [ ] Integrate the shell script into Github Actions
